slam_toolbox:
  ros__parameters:

    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_loss_function: None

    # FRAMES
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan

    # MODE
    mode: localization

    # MAPA A CARGAR
    map_file_name: /home/rubiores/Documents/PAE/lab_1

    # INICIAR EN ORIGEN DEL MAPA
    map_start_pose: [0.0, 0.0, 0.0]

    # DESACTIVAR DOCK
    map_start_at_dock: false

    publish_tf: true

    # DESACTIVAR LOOP CLOSING EN LOCALIZATION
    do_loop_closing: false

    # PUBLISH RATE
    transform_timeout: 0.5
    transform_publish_period: 0.02
    tf_buffer_duration: 30.0

    # ESCANEO
    throttle_scans: 2
    resolution: 0.05
    min_laser_range: 0.2
    max_laser_range: 12.0

    # LOCALIZATION: NO MODIFICAR MAPA
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.2
    minimum_time_interval: 0.5

    use_scan_matching: true
    use_scan_barycenter: true

    # Scan matcher
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true

    # Recursos
    stack_size_to_use: 40000000
