controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names: ["left_wheel_joint"]
      right_wheel_names: ["right_wheel_joint"]
      wheel_separation: 0.18
      wheel_radius: 0.032
      cmd_vel_timeout: 0.5
      publish_rate: 50
      odom_frame_id: "odom"
      base_frame_id: "base_link"
      pose_covariance_diagonal: [0.0001, 0.0001, 0.0001, 0.0, 0.0, 0.0]
      twist_covariance_diagonal: [0.0001, 0.0001, 0.0001, 0.0, 0.0, 0.0]

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.18
    wheel_radius: 0.032
    cmd_vel_timeout: 0.5
    publish_rate: 50
    pose_covariance_diagonal: [0.0001, 0.0001, 0.0001, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0001, 0.0001, 0.0001, 0.0, 0.0, 0.0]
